name = "MyFirstPackage"
uuid = "34887223-d733-4be8-b143-0917602e3213"
authors = ["mingxuzhang"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"   # stdlib 也要在包的 deps 里声明

[compat]
julia = "1.11"  # 先与 CI 的稳定版对齐；跑通后再考虑扩矩阵

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]