name = "MyFirstPackage"
uuid = "34887223-d733-4be8-b143-0917602e3213"
authors = ["mingxuzhang"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CairoMakie = "0.15.6"
LinearAlgebra = "1.11.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
