name = "MyFirstPackage"
uuid = "34887223-d733-4be8-b143-0917602e3213"
authors = ["mingxuzhang"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
